version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "AdvancedMappingCfnMacro"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
s3_prefix = "AdvancedMappingCfnMacro"
